name: integrationTest

on:
  push:
    branches: ["master"]

jobs:
  integrationTest:
    name: integration Test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "11.x"
          cache: gradle
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
          channel: 'stable'
          cache: true
      - name: Flutter tests
        run: flutter test
      - name: Generate apk for testlab
        run: |
            pushd android
            flutter build apk
            ./gradlew app:assembleAndroidTest
            ./gradlew app:assembleDebug -Ptarget="integration_test/sign_in_test.dart"
            popd
      - name: Set up gcloud Cloud SDK environment
      - uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: "integration-test-f"
                        
