name: integrationTest

on:
  push:
    branches: ["main"]

jobs:
  integrationTest:
    name: integration Test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
          cache: gradle
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
          channel: 'stable'
          cache: true

      - name: Flutter tests
        run: flutter test
        
      - name: Generate apk for testlab
        run: |
            pushd android
            flutter build apk
            ./gradlew app:assembleAndroidTest
            ./gradlew app:assembleDebug -Ptarget="integration_test/sign_in_test.dart"
            popd

      - uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: "integration-test-f"
      - name: Download gcloud config json file
        id: gcloud_config
        uses: timheuer/base64-to-file@v1.0.3
        with:
            fileName: integration_test_gcloud.json
            encodedString: ${{  secrets.INTEGRATION_TEST_GCLOUD_CONFIG  }}      
        
      - name: Configure the gcloud account
        run: |
          
           gcloud auth activate-service-account --key-file="${{  steps.gcloud_config.outputs.filePath  }}"
           pushd build
           gcloud firebase test android run --type=instrumentation \
           --app "app/outputs/apk/debug/app-debug.apk" \
           --test "app/outputs/apk/androidTest/debug/app-debug-androidTest.apk" \
           --device-ids=MediumPhone.arm \
           --os-version-ids=33 \
           --orientations=portrait \
           --use-orchestrator \
           --timeout 3m \
           --results-bucket=gs://integration-test-f.appspot.com \
           --results-dir=tests/firebase

                        
